version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  # koristi za razvoj (otkomentariši po potrebi)
      # dockerfile: Dockerfile.prod  # koristi za produkcijuqq
    image: zadruga-backend:dev
    restart: unless-stopped
    volumes:
      - ./backend:/app  
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
       - postgres
    networks:
       - backend-net
       - frontend-net
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
   
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - backend-net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: zadruga-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PYTHONUNBUFFERED=1
    networks:
      - frontend-net
  
  nginx:
    build:
      context: ./nginx
    image: zadruga-nginx:custom
    restart: unless-stopped
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
      - pgadmin
    networks:
      - frontend-net
      - backend-net



networks:
   backend-net:
   frontend-net:
volumes:
  postgres_data:
  node_modules: