"""Initial migration

Revision ID: 2084f7cc07f7
Revises: 
Create Date: 2025-06-17 14:43:08.341615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2084f7cc07f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vestine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naziv')
    )
    op.create_table('korisnik_vestina',
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.Column('vestina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ),
    sa.ForeignKeyConstraint(['vestina_id'], ['vestine.id'], ),
    sa.PrimaryKeyConstraint('korisnik_id', 'vestina_id')
    )
    with op.batch_alter_table('korisnici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum_rodjenja', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('broj_adrese', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('drzavljanstvo', sa.String(length=100), nullable=True))
        batch_op.alter_column('lozinka',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('drzava')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('korisnici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drzava', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('lozinka',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('drzavljanstvo')
        batch_op.drop_column('broj_adrese')
        batch_op.drop_column('datum_rodjenja')

    op.drop_table('korisnik_vestina')
    op.drop_table('vestine')
    # ### end Alembic commands ###
