"""Initial migration

Revision ID: 2d0fd48b530c
Revises: 55a87b411886
Create Date: 2025-05-22 20:48:11.715935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0fd48b530c'
down_revision = '55a87b411886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('lozinka', sa.String(length=128), nullable=False),
    sa.Column('tip_korisnika', sa.Enum('radnik', 'firma', 'admin', name='tipkorisnika'), nullable=False),
    sa.Column('datum_registracije', sa.DateTime(), nullable=True),
    sa.Column('aktivan', sa.Boolean(), nullable=True),
    sa.Column('verifikovan_email', sa.Boolean(), nullable=True),
    sa.Column('profilna_slika', sa.String(length=255), nullable=True),
    sa.Column('biografija', sa.Text(), nullable=True),
    sa.Column('grad', sa.String(length=100), nullable=True),
    sa.Column('adresa', sa.String(length=255), nullable=True),
    sa.Column('drzava', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('block_user', sa.Boolean(), nullable=False),
    sa.Column('prva_rola', sa.Boolean(), nullable=False),
    sa.Column('druga_rola', sa.Boolean(), nullable=False),
    sa.Column('treca_rola', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zanimanja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naziv')
    )
    op.create_table('firme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=150), nullable=False),
    sa.Column('pib', sa.String(length=20), nullable=False),
    sa.Column('adresa', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('web_sajt', sa.String(length=255), nullable=True),
    sa.Column('vlasnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vlasnik_id'], ['korisnici.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pib')
    )
    op.create_table('korisnik_zanimanje',
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.Column('zanimanje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ),
    sa.ForeignKeyConstraint(['zanimanje_id'], ['zanimanja.id'], ),
    sa.PrimaryKeyConstraint('korisnik_id', 'zanimanje_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('korisnik_zanimanje')
    op.drop_table('firme')
    op.drop_table('zanimanja')
    op.drop_table('korisnici')
    # ### end Alembic commands ###
