"""initial migration

Revision ID: 55a87b411886
Revises: 4b35042d27f1
Create Date: 2025-05-21 20:32:43.015478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a87b411886'
down_revision = '4b35042d27f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
