"""Dodato polje id_primaoca u ChatMessage

Revision ID: d3fa58c55434
Revises: f1e271cf985e
Create Date: 2025-10-17 15:42:06.400787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fa58c55434'
down_revision = 'f1e271cf985e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_primaoca', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'korisnici', ['id_primaoca'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_primaoca')

    # ### end Alembic commands ###
