"""dodato polje ocena u Interakcija

Revision ID: f1e271cf985e
Revises: 26ed8dd375f2
Create Date: 2025-10-13 20:39:46.765938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e271cf985e'
down_revision = '26ed8dd375f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interakcije', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocena', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interakcije', schema=None) as batch_op:
        batch_op.drop_column('ocena')

    # ### end Alembic commands ###
